title: Nachiket's Resume
url: 'https://nachiketmparanjape.github.io/cv'

#markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Nachiket Paranjape
tagline: Data Analyst, self-taught programmer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: nachiketm.paranjape@hotmail.com
phone: 716-816-8381
website: nachiketmparanjape.github.io #do not add http://
linkedin: nachiketmparanjape
github: nachiketmparanjape
#twitter: '@webjeda'
instagram: nachiketparanjape
tableau: nachiket.madhav.paranjape

#Update all the sections by editing the files inside _includes folder.

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

